project:
  title: "geostat_ex"
  output-dir: "./docs"
  execute-dir: project
  

editor: visual

number-sections: false
highlight-style: tango
theme: [yeti, theme.scss]
css: style.css
code-block-bg: true
code-block-border-left: "#7AB629"

format: 
  html:
    mainfont: "calibri"
    backgroundcolor: "#eff9fc"
    code-fold: true
    smooth-scroll: true
    toc: false
    grid: 
      sidebar-width: 0px
      margin-width: 0px
      body-width: 2000px

webr: 
  show-startup-message: false    # Disable displaying status of webR initialization